### ISSUE TITLE
Not working after upgrading to 1.0.1.

### ISSUE THREAD

**Issue by jdfrens** [octopress/littlefoot#1]
I upgraded Octopress from 3.0.0 to 3.0.6, ink from 1.0.0.rc to 1.0, and littlefoot from 1.0.0 to 1.0.1.  And now littlefoot doesn't work.  The footnote still appears at the bottom of the post, and the reference is a link to the footnote (as if littlefoot isn't installed at all).  Using my meager JavaScript skills, I was able to confirm that the event listener _is_ added to the footnote reference.

I wiped out the various caches and the generated site itself.  I confirmed that I'm loading the JavaScript and CSS in the head.

I'm happy to help debug this, but I don't know what to try next.

**Comment by imathis** [comment]
Sorry for your troubles! I'll take a look at this tonight.

**Comment by imathis** [comment]
Thanks so much for posting this! I found a fix. In an update to Octopress Ink I changed the default behavior for Javascript to be loaded asynchronously, this means that the `DOMContentLoaded` event may be fired before the javascript is fully downloaded. So I added a check to see if the `document.readyState` was "interactive", in which case I setup LittleFoot immediately.

**Comment by imathis** [comment]
I've just released 1.0.2 which should fix this for you. Thanks again!

**Comment by jdfrens** [comment]
That worked.  Thanks!
